import Header from '@/components/Header/Header';
import type { Metadata } from 'next';
import dynamic from 'next/dynamic';
import localFont from 'next/font/local';
import './globals.css';

const suisse = localFont({
  src: [
    {
      path: './fonts/SuisseIntl-SemiBold.otf',
      weight: '600',
      style: 'semibold',
    },
    {
      path: './fonts/SuisseIntl-Medium.otf',
      weight: '500',
      style: 'medium',
    },
    {
      path: './fonts/SuisseIntl-Book.otf',
      weight: '450',
      style: 'book',
    },
    {
      path: './fonts/SuisseIntl-Regular.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/SuisseIntl-Thin.otf',
      weight: '300',
      style: 'thin',
    },
  ],
  variable: '--font-suisse',
});
export const metadata: Metadata = {
  title: 'Roadmap',
  description: 'Generated by create next app',
};

const NextUIProviders = dynamic(
  () => import('@/components/Providers/NextUIProviders')
);
const SwrProvider = dynamic(() => import('@/components/Providers/SwrProvider'));

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${suisse.className}  antialiased bg-white`}>
        <SwrProvider>
          <NextUIProviders>
            <Header />
            {children}
          </NextUIProviders>
        </SwrProvider>
      </body>
    </html>
  );
}
